<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>s</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~o</string>
	<key>name</key>
	<string>otool</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>comment.line.number-sign.otool</string>
			<key>begin</key>
			<string>#</string>
			<key>end</key>
			<string>$</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.offset.otool</string>
			<key>match</key>
			<string>^[0-9A-Fa-f]+(?=\s|#|$)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.register.otool</string>
			<key>match</key>
			<string>%[A-Za-z_0-9]+\b</string>
		</dict>
		<dict>
			<key>name</key>
			<!-- TODO: Match C/C++/Java labels -->
			<string>storage.modifier.label.otool</string>
			<key>match</key>
			<string>\b[a-zA-Z_][a-zA-Z0-9_]+(?=:)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.otool</string>
			<key>match</key>
			<string>\b(section)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.decimal.otool</string>
			<key>match</key>
			<string>(?:\$-?|-|\b)(?:0x[0-9A-Fa-f]+|[0-9]+)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.byte.otool</string>
			<key>match</key>
			<string>\b[0-9A-Fa-f][0-9A-Fa-f]\b</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.otool</string>
	<key>uuid</key>
	<string>AB158E0D-1643-487C-B680-CD78B1913BD3</string>
</dict>
</plist>
